spring:
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/shareit
    username: dbuser
    password: 12345

logging:
   level.org.springframework:
    orm.jpa: INFO
    orm.jpa.JpaTransactionManager: INFO
    transaction: INFO
    transaction.interceptor: TRACE
